### PR TITLE
Berlin - FullTime - 10.2021 Konstantinos Alexis

### PR DESCRIPTION
**Pull request by kostalexis89**
I just added HTML for the header

### CODE REVIEW

**Comment by kostalexis89** [comment]
I just finished the HTML page. Now I have to give some nice styles with CSS!!!!

**Comment by kostalexis89** [comment]
I am submiting the Challenge ! Cant wait for your feed back

**Comment by Farxa** [comment]
Hi Kostantinos,

well done! This looks very good. The only thing I would change is the search bar, especially try to adjust the width. Try to play around with this I am sure it won't take you too long and it's good training for next week's material ;)

Best, Rahaf (TA)

**Comment by kostalexis89** [comment]
Thank you for your feed back! I made it happen :)
Flexbox is not 100% clear to me yet. I am still a bit uncertain of how its working. I am just playing around until its done !

**Comment by Farxa** [comment]
Great job! We are all still learning and there is always something new to learn coming up... to train your flexbox skills you can check out those two if you'd like:
https://the-echoplex.net/flexyboxes/
https://flexboxfroggy.com/

**Pull request closed without merging**
