### PR TITLE
[Remote-PT-112022] Yeonhwa Park

### PR DESCRIPTION
**Pull request by yosoyyona**
I added some words.

### CODE REVIEW

**Comment by yosoyyona** [comment]
(I think I made a mistake before.)

This version is the right NPM Clone assessments version. 
- I forgot adding a git so I had to do it after I wrote HTML and CSS documentation. 
- The search bar part was really difficult.

**Comment by DaniCalvente** [comment]
Hello!!,

**Comment by DaniCalvente** [comment]
Hello!

**Comment by DaniCalvente** [comment]
Hello!
I am Dani, one of your TA´s, sorry, I'm not sure how do you want me to call you, Yeonhwa or Yona??

I've reviewed your assestment and must say that you have done a good job.
HTML & CSS are well structured, also the HTML semantic is correct.
Just a couple of things to improve:
* The head section is incomplete, there is no language tag, and also the meta tags are missing.
* Wrong paths to the images. You wrote the path to where they are stored in you pc( src="C:\Users\yeona\git-practice\lab-html-exercise\images\black-heart.png" ) so they are not rendered out of your local enviroment, instead you should do like this => src="/images/black-heart.png"

Good job, and stay strong for what is coming💪

**Comment by yosoyyona** [comment]
Hi, Dani!

Just call me Yona! It's easier :-)
Thank you for your review! When I submitted it, already I knew that the
head section was not good😅

Have a good weekend and see you soon!

Yeonhwa Park

2022년 11월 25일 (금) 오후 1:38, DaniCalvente ***@***.***>님이 작성:

**Pull request closed without merging**
